# Generated by Django 4.0.5 on 2022-06-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('creature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cycled_questions.creature')),
            ],
        ),
        migrations.AddField(
            model_name='creature',
            name='current_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_creatures_that_choosed_this_question', to='cycled_questions.question'),
        ),
    ]
